#Importing Libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import warnings
from sklearn import metrics

In [2]:
iris = pd.read_csv("D:\\Projects\\Iris flower detection\\Iris.csv")

In [3]:
iris

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [4]:
iris.head(10)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

In [5]:
iris.drop('Id',axis=1)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [6]:
iris.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

#Splitting data into dependant and independant variables

In [7]:
X = iris.drop('Species', axis=1)
y = iris['Species']
train_x, test_x, train_y, test_y = train_test_split(X, y, test_size = 0.2)

In [8]:
train_x

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
118  119            7.7           2.6            6.9           2.3
112  113            6.8           3.0            5.5           2.1
57    58            4.9           2.4            3.3           1.0
119  120            6.0           2.2            5.0           1.5
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
5      6            5.4           3.9            1.7           0.4
28    29            5.2           3.4            1.4           0.2
75    76            6.6           3.0            4.4           1.4
146  147            6.3           2.5            5.0           1.9
113  114            5.7           2.5            5.0           2.0

[120 rows x 5 columns]

In [9]:
train_y

118     Iris-virginica
112     Iris-virginica
57     Iris-versicolor
119     Iris-virginica
4          Iris-setosa
            ...
5          Iris-setosa
28         Iris-setosa
75     Iris-versicolor
146     Iris-virginica
113     Iris-virginica
Name: Species, Length: 120, dtype: object

In [10]:
model=LogisticRegression()

In [11]:
warnings.filterwarnings("ignore")

In [12]:
model.fit(train_x,train_y)

LogisticRegression()

In [13]:
len(test_x)

30

In [19]:
pred=model.predict(test_x)

In [20]:
val=test_y

In [21]:
print("Accuracy of model = ",metrics.accuracy_score(pred,val))

Accuracy of model =  1.0

In [22]:
pred

array(['Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor'],
      dtype=object)

In [26]:
val=pd.DataFrame(val)

In [27]:
val

             Species
29       Iris-setosa
13       Iris-setosa
63   Iris-versicolor
37       Iris-setosa
46       Iris-setosa
132   Iris-virginica
138   Iris-virginica
105   Iris-virginica
15       Iris-setosa
82   Iris-versicolor
131   Iris-virginica
56   Iris-versicolor
55   Iris-versicolor
25       Iris-setosa
12       Iris-setosa
86   Iris-versicolor
16       Iris-setosa
114   Iris-virginica
102   Iris-virginica
35       Iris-setosa
3        Iris-setosa
59   Iris-versicolor
127   Iris-virginica
54   Iris-versicolor
111   Iris-virginica
31       Iris-setosa
79   Iris-versicolor
83   Iris-versicolor
100   Iris-virginica
96   Iris-versicolor